### ISSUE TITLE
how am i suppose to compile it

### ISSUE THREAD

**Issue by theawsomeavr** [adafruit/Adafruit-Trinket-Gemma-Bootloader#2]
hi, i been wanted to compile the bootloader with WINavr and so when i tipe on cmd make a bunch of hex files get created. i flash all of the to my attiny85 and none of them work.
the fuses are set correctly, i also notice that none of the hex files have the exact same size as the trinketgemma_v1.hex that comes precompiled

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-Trinket-Gemma-Bootloader/blob/master/Makefile

**Comment by ladyada** [comment]
hiya the makefile should work, we only tested it on the gemma/trinket - we dont have any tutorials or tech support for DIY boards at this time :)

**Comment by theawsomeavr** [comment]
well i mean that i have trinket and i just burn try to burn the bootloader on it using a usbasp

**Comment by ladyada** [comment]
here is how to do it https://learn.adafruit.com/introducing-trinket/repairing-bootloader

**Comment by ladyada** [comment]
if you have more questions and you have an adafruit product, please post the forum, we dont do tech support in github issues  :)
thanx!

**Comment by theawsomeavr** [comment]
thanks, but i want to compile the bootloader with a modified version of the boot.c file so that i can enter to bootloader mode if a press a button on PIN0
